### ISSUE TITLE
Implement WithMinimumLevelForSourceContext for several contexts

### ISSUE THREAD

**Issue by scklepova** [vostok/logging.abstractions#10]
To filter events with several specific source contexts by level.

E.g. There is a library, the library sends logs with its own sourceContext (L) and is used in several services (X and Y). One wants to monitor that services in different ways. So, he passes logger wrapped with service's context (X or Y) to the library and configures logging differently for (L, X) and (L, Y).

**Comment by AndrewKostousov** [comment]
Another use case for this feature is a library which performs its logging in "nested contexts" manner. Consider library code sketch:
``` C#
public class MyLibraryEntryPoint
{
    private readonly ILog log;

    public MyLibraryEntryPoint(ILog log)
    {
        this.log = log.ForContext("MyLibrary");
    }

    public void Foo()
    {
        log.Info("Foo");

        var impl = new ImplementationDetails(log);
        impl.Bar();
    }
}

internal class MyLibraryImplementationDetails
{
    private readonly ILog log;

    public MyLibraryImplementationDetails(ILog log)
    {
        this.log = log.ForContext("ImplementationDetails");
    }

    public void Bar()
    {
        log.Info("Bar");
    }
}
```
When using such a library one would like to configure her logging system to filter out logs corresponding to `MyLibraryImplementationDetails`, i.e. logs with a pair of source contexts (`"MyLibrary", "ImplementationDetails"`).

Note that library author cannot just write `MyLibraryImplementationDetails` logs with e.g. `DEBUG` level since the other client may wish to see all logs produced by this library.
